on:
  push:
    paths:
      DredgeClient/**
  workflow_dispatch:

jobs:
  Build-Jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
      - name: build
        run: |
          cd DredgeClient
          chmod +x ./gradlew
          ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Artifacts
          path: build/libs/
