on:
  push:
    paths:
      - DredgeDevDimension/**

jobs:
  Build-Datapack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: DredgeDevDimension/data/ DredgeDevDimension/pack.mcmeta
          dest: DredgeDevDimension.zip
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: DredgeDevDimension
          path: ${{ github.workspace }}/DredgeDevDimension.zip
