on:
  push:
    paths:
      - DredgeForgeSimple/**

jobs:
  Build-Datapack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: DredgeForgeSimple
          path: DredgeForgeSimple/**
