on:
  push:
    paths:
      - DredgeResources/**

jobs:
  Build-Resourcepack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: DredgeResources
          path: DredgeResources/**
