on:
  push:
    paths:
      - DredgeTrinkets/**
  workflow_dispatch:

jobs:
  Build-Datapack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: DredgeTrinkets
          path: DredgeTrinkets/**
